baseURL = "https://shaaf.dev"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Shaaf's Blog"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
disqusShortname = "https-shaaf-dev"

# Google Analytics
googleAnalytics = "UA-58961685-1"

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true