baseurl = "https://shaaf.dev"
title = "Shaaf's blog"
theme = "hugo-theme-cleanwhite"
languageCode = "en-us"
preserveTaxonomyNames = true
hasCJKLanguage = true

[services]
  [services.googleAnalytics]
    id = "G-72FCXF4TY5"


[pagination]
  pagerSize = 5 # frontpage pagination

[outputs]
home = ["HTML", "RSS", "Algolia"]

[params]
  header_image = "images/jupiter.jpeg"
  #og_image =  "images/jupiter.jpeg"
  SEOTitle = "Syed M Shaaf's Blog | All about software development and encouters there about"
  description = "A technical blog about Java, Kubernetes and things that matter"
  keyword = "Java, developers, devops, , kubernetes, redhat, Shaaf Blog, Web, keycloak, PaaS, Istio, Kubernetes, infinispan, Microservice"
  slogan = "A technical blog about Java, Kubernetes and things that matter"

  plantuml = true
  image_404 = "img/404-bg.jpg"
  title_404 = "Something was lost... :("
  omit_categories = false

  # algolia site search
  algolia_search = true
  algolia_appId = "WJ4GQV8C8J"
  algolia_indexName = "dev_shaaf"
  algolia_apiKey = "49ebe99eba591b32ef02c82ede21718a"

  # Sidebar settings
  sidebar_about_description = "Software developer, architect, opensource enthusiast, cricket coach"
  sidebar_avatar = "images/shaaf_rh900x900.jpeg"      # use absolute URL, seeing it's used in both `/` and `/about/`

  featured_tags = true 
  featured_condition_size = 1 

  #Enable wechat pay & alipay to allow readers send reward money if they like the articles 
  reward = false
  # reward_guide = "如果这篇文章对你有用,请随意打赏" 

  friends = false
  bookmarks = false
  about_me = true

  [params.social]
  rss            = true 
  twitter        = "https://twitter.com/syshaaf"
  linkedin       = "https://www.linkedin.com/in/shaaf/"
  stackoverflow  = "https://stackoverflow.com/users/243185/syed-m-shaaf"
  github         = "https://github.com/sshaaf"
  mastodon      = "https://fosstodon.org/@shaaf"
  

  [[params.additional_menus]]
  title =  "Articles"
  href =  "/articles"

  [[params.additional_menus]]
  title =  "Conferences"
  href =  "/conferences"

  [[params.additional_menus]]
  title =  "ARCHIVE"
  href =  "/archive"
  
  [[params.additional_menus]]
  title =  "WORKSHOPS"
  href =  "/workshops"

  [[params.additional_menus]]
  title =  "ABOUT"
  href =  "/about"

 [[params.additional_menus]]
  title =  "SEARCH"
  href =  "/search"

  [params.giscus]
  data_repo = "sshaaf/sshaaf.github.io"
  data_repo_id = "R_kgDOI8ZtWg"
  data_category = "Announcements"
  data_category_id = "DIC_kwDOI8ZtWs4CUIWK"
  data_mapping = "pathname"
  data_reactions_enabled = "1"
  data_emit_metadata = "0"
  data_theme = "light"
  data_lang = "en"
  crossorigin = "anonymous"

  [outputFormats.Algolia]
  baseName = "algolia"
  isPlainText = true
  mediaType = "application/json"
  notAlternative = true

  [params.algolia]
  vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
  params = ["categories", "tags"] 

  [markup]
    [markup.tableOfContents]
      endLevel = 2
      startLevel = 1
    [markup.highlight]
      style = "dracula"
    [markup.goldmark]
      [markup.goldmark.renderer]
        unsafe = true