baseurl = "https://shaaf.dev"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
title = "Shaaf's Blog"
canonifyurls  = true

DefaultContentLanguage = "en"
theme = "hugo-theme-hello-friend-ng"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
#disqusShortname = "XXX"
#googleAnalytics = "XXX"


[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Shaaf's Blog"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = true

  # Enable sharing buttons, if you linke
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "A place where I can blog about the things I do or come across everyday"
  keywords = "homepage, blog"
  images = [""]

[taxonomies]
    category = "posts"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Shaaf's blog"
    subtitle = "A blog about programming and other things.."
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Welcome!"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "Posts"
    name       = "Posts"
    url        = "/post"

  [[menu.main]]
        name = "Tags"
        url = "tags"
